# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSoXSVacuumMINI.ui'
#
# Created: Mon Apr 15 15:15:49 2019
#      by: qtpy-uic 2.0.4
#
# WARNING! All changes made in this file will be lost!
import os
from pydm import Display
from qtpy import QtCore, QtGui, QtWidgets
from pydm.widgets import PyDMEmbeddedDisplay, PyDMByteIndicator, PyDMLabel, PyDMRelatedDisplayButton

class RSoXSminivac(Display):
    def __init__(self, parent=None, args=[], macros=None):
        super(RSoXSminivac, self).__init__(parent=parent, args=args, macros=None)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(1049, 124)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(626, 60))
        Form.setMaximumSize(QtCore.QSize(1280, 600))
        Form.setWindowOpacity(0.7)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PyDMByteIndicator_15 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_15.setToolTip("")
        self.PyDMByteIndicator_15.setProperty("onColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_15.setProperty("offColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_15.setProperty("showLabels", False)
        self.PyDMByteIndicator_15.setObjectName("PyDMByteIndicator_15")
        self.gridLayout.addWidget(self.PyDMByteIndicator_15, 7, 12, 2, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 7, 7, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 11, 2, 3)
        self.PyDMByteIndicator_5 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_5.setToolTip("")
        self.PyDMByteIndicator_5.setProperty("showLabels", False)
        self.PyDMByteIndicator_5.setObjectName("PyDMByteIndicator_5")
        self.gridLayout.addWidget(self.PyDMByteIndicator_5, 7, 8, 2, 1)
        self.PyDMByteIndicator_16 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_16.setToolTip("")
        self.PyDMByteIndicator_16.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_16.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_16.setProperty("showLabels", False)
        self.PyDMByteIndicator_16.setObjectName("PyDMByteIndicator_16")
        self.gridLayout.addWidget(self.PyDMByteIndicator_16, 7, 13, 2, 1)
        self.PyDMByteIndicator_17 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_17.setToolTip("")
        self.PyDMByteIndicator_17.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_17.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_17.setProperty("showLabels", False)
        self.PyDMByteIndicator_17.setObjectName("PyDMByteIndicator_17")
        self.gridLayout.addWidget(self.PyDMByteIndicator_17, 7, 14, 2, 1)
        self.PyDMLabel = PyDMLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.PyDMLabel.setFont(font)
        self.PyDMLabel.setToolTip("")
        self.PyDMLabel.setObjectName("PyDMLabel")
        self.gridLayout.addWidget(self.PyDMLabel, 0, 0, 7, 2)
        self.PyDMByteIndicator = PyDMByteIndicator(Form)
        self.PyDMByteIndicator.setMinimumSize(QtCore.QSize(0, 10))
        self.PyDMByteIndicator.setMaximumSize(QtCore.QSize(16777215, 10))
        self.PyDMByteIndicator.setProperty("showLabels", False)
        self.PyDMByteIndicator.setObjectName("PyDMByteIndicator")
        self.gridLayout.addWidget(self.PyDMByteIndicator, 0, 2, 3, 1)
        self.PyDMLabel_2 = PyDMLabel(Form)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.PyDMLabel_2.setFont(font)
        self.PyDMLabel_2.setToolTip("")
        self.PyDMLabel_2.setObjectName("PyDMLabel_2")
        self.gridLayout.addWidget(self.PyDMLabel_2, 0, 8, 7, 2)
        self.PyDMByteIndicator_13 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_13.setToolTip("")
        self.PyDMByteIndicator_13.setProperty("onColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_13.setProperty("offColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_13.setProperty("showLabels", False)
        self.PyDMByteIndicator_13.setObjectName("PyDMByteIndicator_13")
        self.gridLayout.addWidget(self.PyDMByteIndicator_13, 7, 10, 2, 1)
        self.PyDMByteIndicator_11 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_11.setMinimumSize(QtCore.QSize(0, 10))
        self.PyDMByteIndicator_11.setMaximumSize(QtCore.QSize(16777215, 10))
        self.PyDMByteIndicator_11.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_11.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_11.setProperty("showLabels", False)
        self.PyDMByteIndicator_11.setObjectName("PyDMByteIndicator_11")
        self.gridLayout.addWidget(self.PyDMByteIndicator_11, 0, 3, 3, 1)
        self.PyDMLabel_4 = PyDMLabel(Form)
        self.PyDMLabel_4.setMinimumSize(QtCore.QSize(135, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.PyDMLabel_4.setFont(font)
        self.PyDMLabel_4.setToolTip("")
        self.PyDMLabel_4.setObjectName("PyDMLabel_4")
        self.gridLayout.addWidget(self.PyDMLabel_4, 7, 6, 3, 1)
        self.PyDMLabel_3 = PyDMLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.PyDMLabel_3.setFont(font)
        self.PyDMLabel_3.setToolTip("")
        self.PyDMLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PyDMLabel_3.setProperty("precisionFromPV", False)
        self.PyDMLabel_3.setProperty("precision", 2)
        self.PyDMLabel_3.setProperty("showUnits", True)
        self.PyDMLabel_3.setProperty("displayFormat", PyDMLabel.Decimal)
        self.PyDMLabel_3.setObjectName("PyDMLabel_3")
        self.gridLayout.addWidget(self.PyDMLabel_3, 0, 6, 7, 1)
        self.PyDMByteIndicator_3 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_3.setToolTip("")
        self.PyDMByteIndicator_3.setProperty("showLabels", False)
        self.PyDMByteIndicator_3.setObjectName("PyDMByteIndicator_3")
        self.gridLayout.addWidget(self.PyDMByteIndicator_3, 7, 4, 2, 1)
        self.PyDMByteIndicator_9 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_9.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_9.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_9.setProperty("showLabels", False)
        self.PyDMByteIndicator_9.setObjectName("PyDMByteIndicator_9")
        self.gridLayout.addWidget(self.PyDMByteIndicator_9, 9, 3, 1, 1)
        self.PyDMByteIndicator_12 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_12.setToolTip("")
        self.PyDMByteIndicator_12.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_12.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_12.setProperty("showLabels", False)
        self.PyDMByteIndicator_12.setObjectName("PyDMByteIndicator_12")
        self.gridLayout.addWidget(self.PyDMByteIndicator_12, 7, 9, 2, 1)
        self.PyDMByteIndicator_6 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_6.setProperty("orientation", QtCore.Qt.Horizontal)
        self.PyDMByteIndicator_6.setProperty("showLabels", False)
        self.PyDMByteIndicator_6.setProperty("numBits", 1)
        self.PyDMByteIndicator_6.setObjectName("PyDMByteIndicator_6")
        self.gridLayout.addWidget(self.PyDMByteIndicator_6, 9, 2, 1, 1)
        self.PyDMLabel_6 = PyDMLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.PyDMLabel_6.setFont(font)
        self.PyDMLabel_6.setToolTip("")
        self.PyDMLabel_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PyDMLabel_6.setProperty("showUnits", True)
        self.PyDMLabel_6.setObjectName("PyDMLabel_6")
        self.gridLayout.addWidget(self.PyDMLabel_6, 2, 11, 5, 4)
        self.PyDMByteIndicator_2 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_2.setMinimumSize(QtCore.QSize(0, 10))
        self.PyDMByteIndicator_2.setMaximumSize(QtCore.QSize(16777215, 10))
        self.PyDMByteIndicator_2.setProperty("showLabels", False)
        self.PyDMByteIndicator_2.setObjectName("PyDMByteIndicator_2")
        self.gridLayout.addWidget(self.PyDMByteIndicator_2, 3, 2, 1, 1)
        self.PyDMByteIndicator_4 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_4.setToolTip("")
        self.PyDMByteIndicator_4.setProperty("showLabels", False)
        self.PyDMByteIndicator_4.setObjectName("PyDMByteIndicator_4")
        self.gridLayout.addWidget(self.PyDMByteIndicator_4, 7, 7, 2, 1)
        self.PyDMByteIndicator_10 = PyDMByteIndicator(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PyDMByteIndicator_10.sizePolicy().hasHeightForWidth())
        self.PyDMByteIndicator_10.setSizePolicy(sizePolicy)
        self.PyDMByteIndicator_10.setMinimumSize(QtCore.QSize(0, 10))
        self.PyDMByteIndicator_10.setMaximumSize(QtCore.QSize(16777215, 10))
        self.PyDMByteIndicator_10.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_10.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_10.setProperty("orientation", QtCore.Qt.Horizontal)
        self.PyDMByteIndicator_10.setProperty("showLabels", False)
        self.PyDMByteIndicator_10.setObjectName("PyDMByteIndicator_10")
        self.gridLayout.addWidget(self.PyDMByteIndicator_10, 3, 3, 1, 1)
        self.PyDMByteIndicator_8 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_8.setToolTip("")
        self.PyDMByteIndicator_8.setProperty("onColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_8.setProperty("offColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_8.setProperty("showLabels", False)
        self.PyDMByteIndicator_8.setObjectName("PyDMByteIndicator_8")
        self.gridLayout.addWidget(self.PyDMByteIndicator_8, 7, 0, 2, 1)
        self.PyDMByteIndicator_18 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_18.setToolTip("")
        self.PyDMByteIndicator_18.setProperty("onColor", QtGui.QColor(7, 19, 255))
        self.PyDMByteIndicator_18.setProperty("offColor", QtGui.QColor(240, 240, 240))
        self.PyDMByteIndicator_18.setProperty("numBits", 2)
        self.PyDMByteIndicator_18.setProperty("labels", ['Decay', 'TopOff'])
        self.PyDMByteIndicator_18.setObjectName("PyDMByteIndicator_18")
        self.gridLayout.addWidget(self.PyDMByteIndicator_18, 1, 10, 5, 1)
        self.PyDMLabel_8 = PyDMLabel(Form)
        self.PyDMLabel_8.setToolTip("")
        self.PyDMLabel_8.setObjectName("PyDMLabel_8")
        self.gridLayout.addWidget(self.PyDMLabel_8, 0, 14, 2, 1)
        self.PyDMByteIndicator_14 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_14.setToolTip("")
        self.PyDMByteIndicator_14.setProperty("onColor", QtGui.QColor(0, 255, 0))
        self.PyDMByteIndicator_14.setProperty("offColor", QtGui.QColor(100, 100, 100))
        self.PyDMByteIndicator_14.setProperty("showLabels", False)
        self.PyDMByteIndicator_14.setObjectName("PyDMByteIndicator_14")
        self.gridLayout.addWidget(self.PyDMByteIndicator_14, 7, 11, 2, 1)
        self.PyDMByteIndicator_7 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_7.setToolTip("")
        self.PyDMByteIndicator_7.setProperty("showLabels", False)
        self.PyDMByteIndicator_7.setObjectName("PyDMByteIndicator_7")
        self.gridLayout.addWidget(self.PyDMByteIndicator_7, 7, 1, 2, 1)
        self.MainCCG = PyDMLabel(Form)
        self.MainCCG.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.MainCCG.setFont(font)
        self.MainCCG.setToolTip("")
        self.MainCCG.setProperty("showUnits", True)
        self.MainCCG.setObjectName("MainCCG")
        self.gridLayout.addWidget(self.MainCCG, 5, 2, 4, 2)
        self.PyDMByteIndicator_19 = PyDMByteIndicator(Form)
        self.PyDMByteIndicator_19.setMaximumSize(QtCore.QSize(20, 16777215))
        self.PyDMByteIndicator_19.setToolTip("")
        self.PyDMByteIndicator_19.setProperty("showLabels", False)
        self.PyDMByteIndicator_19.setProperty("circles", True)
        self.PyDMByteIndicator_19.setObjectName("PyDMByteIndicator_19")
        self.gridLayout.addWidget(self.PyDMByteIndicator_19, 7, 5, 2, 1)
        self.PyDMRelatedDisplayButton = PyDMRelatedDisplayButton(Form)
        self.PyDMRelatedDisplayButton.setToolTip("")
        self.PyDMRelatedDisplayButton.setProperty("openInNewWindow", True)
        self.PyDMRelatedDisplayButton.setObjectName("PyDMRelatedDisplayButton")
        self.gridLayout.addWidget(self.PyDMRelatedDisplayButton, 0, 4, 7, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("", "RSoXS Vacuum Monitor", None, -1))
        self.PyDMByteIndicator_15.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDA-VA:2{FS:6-GV:1}Pos-Sts", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("", "mA", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "Next Inj:", None, -1))
        self.PyDMByteIndicator_5.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{Mir:M3C-GV:1}Pos-Sts", None, -1))
        self.PyDMByteIndicator_16.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDA-PPS{PSh:4}Pos-Sts", None, -1))
        self.PyDMByteIndicator_17.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07ID-PPS{Sh:FE}Pos-Sts", None, -1))
        self.PyDMLabel.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:LL-CCG:1}P:Raw-I", None, -1))
        self.PyDMByteIndicator.setToolTip(QtWidgets.QApplication.translate("", "Opened", None, -1))
        self.PyDMByteIndicator.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:TP-GV:1}Pos-Sts", None, -1))
        self.PyDMLabel_2.setProperty("channel", QtWidgets.QApplication.translate("", "ca://SR-OPS{}Mode-Sts", None, -1))
        self.PyDMByteIndicator_13.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{Mono:PGM-GV:1}Pos-Sts", None, -1))
        self.PyDMByteIndicator_11.setToolTip(QtWidgets.QApplication.translate("", "Not Closed", None, -1))
        self.PyDMByteIndicator_11.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:TP-GV:1}Sw:ClsLim-Sts", None, -1))
        self.PyDMLabel_4.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:DM-CCG:1}P:Raw-I", None, -1))
        self.PyDMLabel_3.setProperty("channel", QtWidgets.QApplication.translate("", "ca://SR:OPS-BI{DCCT:1}I:Real-I", None, -1))
        self.PyDMByteIndicator_3.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:Main-GV:1}Pos-Sts", None, -1))
        self.PyDMByteIndicator_9.setToolTip(QtWidgets.QApplication.translate("", "Not Closed", None, -1))
        self.PyDMByteIndicator_9.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:Main-GV:2}Sw:ClsLim-Sts", None, -1))
        self.PyDMByteIndicator_12.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDA-PPS{PSh:10}Pos-Sts", None, -1))
        self.PyDMByteIndicator_6.setToolTip(QtWidgets.QApplication.translate("", "Opened", None, -1))
        self.PyDMByteIndicator_6.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:Main-GV:2}Pos-Sts", None, -1))
        self.PyDMLabel_6.setProperty("channel", QtWidgets.QApplication.translate("", "ca://OP-CT{IOC:opsum}:TOD", None, -1))
        self.PyDMByteIndicator_2.setToolTip(QtWidgets.QApplication.translate("", "Opened", None, -1))
        self.PyDMByteIndicator_2.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:LL-GV:1}Pos-Sts", None, -1))
        self.PyDMByteIndicator_4.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:3{Slt:C-GV:1}Pos-Sts", None, -1))
        self.PyDMByteIndicator_10.setToolTip(QtWidgets.QApplication.translate("", "Not Closed", None, -1))
        self.PyDMByteIndicator_10.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:LL-GV:1}Sw:ClsLim-Sts", None, -1))
        self.PyDMByteIndicator_8.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDA-PPS{PSh:7}Pos-Sts", None, -1))
        self.PyDMByteIndicator_18.setProperty("channel", QtWidgets.QApplication.translate("", "ca://INJ{TOC}OpControl-Sel", None, -1))
        self.PyDMLabel_8.setProperty("channel", QtWidgets.QApplication.translate("", "ca://INJ{TOC-SM}Cnt:Next-I", None, -1))
        self.PyDMByteIndicator_14.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDA-VA:2{FS:6-GV:2}Pos-Sts", None, -1))
        self.PyDMByteIndicator_7.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{BT:1-GV:1}Pos-Sts", None, -1))
        self.MainCCG.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-VA:2{RSoXS:Main-CCG:1}P:Raw-I", None, -1))
        self.PyDMByteIndicator_19.setProperty("channel", QtWidgets.QApplication.translate("", "ca://XF:07IDB-CT{DIODE-Local:1}OutPt01:Data-Sel", None, -1))
        self.PyDMRelatedDisplayButton.setText(QtWidgets.QApplication.translate("", "Valve\n"
"Control", None, -1))
        self.PyDMRelatedDisplayButton.setProperty("displayFilename", QtWidgets.QApplication.translate("", "RSoXSVacuum.ui", None, -1))

